
package com.test.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SayPapayaaService", targetNamespace = "http://impl.test.com/", wsdlLocation = "http://localhost:8080/TestMyUnderstanding/saypapaya1?wsdl")
public class SayPapayaaService
    extends Service
{

    private final static URL SAYPAPAYAASERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYPAPAYAASERVICE_EXCEPTION;
    private final static QName SAYPAPAYAASERVICE_QNAME = new QName("http://impl.test.com/", "SayPapayaaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TestMyUnderstanding/saypapaya1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYPAPAYAASERVICE_WSDL_LOCATION = url;
        SAYPAPAYAASERVICE_EXCEPTION = e;
    }

    public SayPapayaaService() {
        super(__getWsdlLocation(), SAYPAPAYAASERVICE_QNAME);
    }

    public SayPapayaaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAYPAPAYAASERVICE_QNAME, features);
    }

    public SayPapayaaService(URL wsdlLocation) {
        super(wsdlLocation, SAYPAPAYAASERVICE_QNAME);
    }

    public SayPapayaaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAYPAPAYAASERVICE_QNAME, features);
    }

    public SayPapayaaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayPapayaaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SayPapaya
     */
    @WebEndpoint(name = "SayPapayaaPort")
    public SayPapaya getSayPapayaaPort() {
        return super.getPort(new QName("http://impl.test.com/", "SayPapayaaPort"), SayPapaya.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayPapaya
     */
    @WebEndpoint(name = "SayPapayaaPort")
    public SayPapaya getSayPapayaaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.test.com/", "SayPapayaaPort"), SayPapaya.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYPAPAYAASERVICE_EXCEPTION!= null) {
            throw SAYPAPAYAASERVICE_EXCEPTION;
        }
        return SAYPAPAYAASERVICE_WSDL_LOCATION;
    }

}
