
package com.test.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SayPapaya", targetNamespace = "http://test.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SayPapaya {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://test.com/SayPapaya/sayPapayaRequest", output = "http://test.com/SayPapaya/sayPapayaResponse")
    public String sayPapaya(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://test.com/SayPapaya/sayPotatoRequest", output = "http://test.com/SayPapaya/sayPotatoResponse")
    public String sayPotato(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
